FROM archlinux/archlinux
RUN pacman -Syuu --needed --noconfirm \
        base-devel \
        coreutils jq \
        gptfdisk btrfs-progs dosfstools qemu-img \
        arch-install-scripts \
        github-cli vagrant
